/** Step notes for the tree engines (`lib/simulations/trees.ts`). */
export const en = {
  // BST
  "n.bst.root": "Tree empty — {key} becomes the root.",
  "n.bst.insertCompare": "Insert {key}: compare with {node}.",
  "n.bst.insertLeft": "{key} < {node} — insert as left child.",
  "n.bst.insertRight": "{key} > {node} — insert as right child.",
  "n.bst.duplicate": "{key} already present — no change.",
  "n.bst.built": "Built the BST from [{seq}].",
  "n.bst.searchAt": "Search {key}: at {node}.",
  "n.bst.found": "Found {key}.",
  "n.bst.moveLeft": "{key} < node — move left.",
  "n.bst.moveRight": "{key} > node — move right.",
  "n.bst.notFound": "{key} is not in the tree.",
  "n.bst.delMissing": "{key} not found — nothing to delete.",
  "n.bst.delAt": "Delete {key}: at {node}.",
  "n.bst.delFound": "Found {key} — remove this node.",
  "n.bst.delSuccessor": "Two children — copy successor {succ} up.",
  "n.bst.deleted": "Deleted {key} — BST property preserved.",

  // AVL
  "n.avl.leaf": "Insert {key} as a new leaf.",
  "n.avl.compare": "Insert {key}: compare with {node}.",
  "n.avl.bf": "Balance factor of {node} is {bf}.",
  "n.avl.ll": "Left-Left case at {node} — rotate right.",
  "n.avl.rotatedRight": "Rotated right around {node}.",
  "n.avl.rr": "Right-Right case at {node} — rotate left.",
  "n.avl.rotatedLeft": "Rotated left around {node}.",
  "n.avl.lr": "Left-Right case at {node} — rotate left then right.",
  "n.avl.rl": "Right-Left case at {node} — rotate right then left.",
  "n.avl.doubleDone": "Double rotation done at {node}.",
  "n.avl.done": "AVL tree stays height-balanced after every insert.",

  // Binary heap
  "n.heap.push": "Push {value} at the end (index {index}).",
  "n.heap.siftUp": "Sift-up: compare {value} with parent {parent}.",
  "n.heap.swapUp": "{big} > {small} — swap up.",
  "n.heap.built": "Max-heap built — root holds the maximum.",
  "n.heap.pop": "Pop: remove root {value}.",
  "n.heap.empty": "Heap is empty after popping {value}.",
  "n.heap.moveLast": "Move last element {value} to the root.",
  "n.heap.siftDown": "Sift-down: compare with children.",
  "n.heap.restored": "Heap property restored.",
  "n.heap.swapDown": "Swap {value} down.",

  // Trie
  "n.trie.create": "Insert \"{word}\": create node for '{ch}'.",
  "n.trie.descend": "Insert \"{word}\": '{ch}' already exists — descend.",
  "n.trie.end": "Mark end of word \"{word}\".",
  "n.trie.missing": "Search \"{query}\": '{ch}' missing — not found.",
  "n.trie.match": "Search \"{query}\": match '{ch}' — descend.",
  "n.trie.word": "\"{query}\" is a complete word.",
  "n.trie.prefix": "\"{query}\" is a valid prefix.",

  // Segment tree
  "n.seg.empty": "The array is empty — there is no segment tree to build.",
  "n.seg.leaf": "Leaf [{index}] = {value}.",
  "n.seg.combine": "Combine [{lo},{hi}] = {left} + {right} = {sum}.",
  "n.seg.built": "Segment tree built — root sum = {sum}.",
  "n.seg.outside": "[{lo},{hi}] outside [{ql},{qr}] — contributes 0.",
  "n.seg.inside": "[{lo},{hi}] fully inside — take {sum}.",
  "n.seg.split": "[{lo},{hi}] partially overlaps — split.",
  "n.seg.total": "Sum over [{ql}, {qr}] = {total}.",

  // Union-Find
  "n.uf.makeSets": "makeSets({n}): every element is its own root with rank 0.",
  "n.uf.walk": "find({x}): {node} is not a root — follow parent[{node}] = {parent}.",
  "n.uf.root": "find({x}) = {root} — the root represents the set.",
  "n.uf.compressOne": "Path compression: {nodes} now points straight at {root}.",
  "n.uf.compress": "Path compression: {nodes} now point straight at {root}.",
  "n.uf.sameSet": "{op}: both are already in set {root} — nothing to do.",
  "n.uf.unionLess": "{op}: rank {rankA} < {rankB} — hang root {ra} under {rb}.",
  "n.uf.unionGreater": "{op}: rank {rankA} > {rankB} — hang root {rb} under {ra}.",
  "n.uf.unionEqual":
    "{op}: equal ranks — hang {rb} under {ra} and bump rank[{ra}] to {rank}.",
  "n.uf.done":
    "Done. find({key}) = {root}; repeated finds have flattened the forest.",
} as const;

export const tr: Partial<Record<keyof typeof en, string>> = {
  "n.bst.root": "Ağaç boş — {key} kök oluyor.",
  "n.bst.insertCompare": "{key} ekleniyor: {node} ile karşılaştırılıyor.",
  "n.bst.insertLeft": "{key} < {node} — sol çocuk olarak ekleniyor.",
  "n.bst.insertRight": "{key} > {node} — sağ çocuk olarak ekleniyor.",
  "n.bst.duplicate": "{key} zaten var — değişiklik yok.",
  "n.bst.built": "[{seq}] dizisinden BST kuruldu.",
  "n.bst.searchAt": "{key} aranıyor: {node} düğümündeyiz.",
  "n.bst.found": "{key} bulundu.",
  "n.bst.moveLeft": "{key} < düğüm — sola gidiliyor.",
  "n.bst.moveRight": "{key} > düğüm — sağa gidiliyor.",
  "n.bst.notFound": "{key} ağaçta yok.",
  "n.bst.delMissing": "{key} bulunamadı — silinecek bir şey yok.",
  "n.bst.delAt": "{key} siliniyor: {node} düğümündeyiz.",
  "n.bst.delFound": "{key} bulundu — bu düğüm kaldırılıyor.",
  "n.bst.delSuccessor": "İki çocuk var — ardıl {succ} yukarı kopyalanıyor.",
  "n.bst.deleted": "{key} silindi — BST özelliği korundu.",

  "n.avl.leaf": "{key} yeni bir yaprak olarak ekleniyor.",
  "n.avl.compare": "{key} ekleniyor: {node} ile karşılaştırılıyor.",
  "n.avl.bf": "{node} düğümünün denge faktörü {bf}.",
  "n.avl.ll": "{node} düğümünde Sol-Sol durumu — sağa döndürülüyor.",
  "n.avl.rotatedRight": "{node} çevresinde sağa döndürüldü.",
  "n.avl.rr": "{node} düğümünde Sağ-Sağ durumu — sola döndürülüyor.",
  "n.avl.rotatedLeft": "{node} çevresinde sola döndürüldü.",
  "n.avl.lr": "{node} düğümünde Sol-Sağ durumu — önce sola, sonra sağa döndürülüyor.",
  "n.avl.rl": "{node} düğümünde Sağ-Sol durumu — önce sağa, sonra sola döndürülüyor.",
  "n.avl.doubleDone": "{node} düğümünde çift döndürme tamamlandı.",
  "n.avl.done": "AVL ağacı her eklemeden sonra yükseklik dengesini korur.",

  "n.heap.push": "{value} sona ekleniyor ({index}. indeks).",
  "n.heap.siftUp": "Yukarı süzme: {value} ile ebeveyn {parent} karşılaştırılıyor.",
  "n.heap.swapUp": "{big} > {small} — yukarı takas.",
  "n.heap.built": "Max-heap kuruldu — kök en büyüğü tutuyor.",
  "n.heap.pop": "Çıkarma: kök {value} kaldırılıyor.",
  "n.heap.empty": "{value} çıkarıldıktan sonra heap boşaldı.",
  "n.heap.moveLast": "Son eleman {value} köke taşınıyor.",
  "n.heap.siftDown": "Aşağı süzme: çocuklarla karşılaştırılıyor.",
  "n.heap.restored": "Heap özelliği yeniden sağlandı.",
  "n.heap.swapDown": "{value} aşağı takas ediliyor.",

  "n.trie.create": "\"{word}\" ekleniyor: '{ch}' için düğüm oluşturuluyor.",
  "n.trie.descend": "\"{word}\" ekleniyor: '{ch}' zaten var — aşağı iniliyor.",
  "n.trie.end": "\"{word}\" kelimesinin sonu işaretleniyor.",
  "n.trie.missing": "\"{query}\" aranıyor: '{ch}' yok — bulunamadı.",
  "n.trie.match": "\"{query}\" aranıyor: '{ch}' eşleşti — aşağı iniliyor.",
  "n.trie.word": "\"{query}\" tam bir kelime.",
  "n.trie.prefix": "\"{query}\" geçerli bir ön ek.",

  "n.seg.empty": "Dizi boş — kurulacak bir segment ağacı yok.",
  "n.seg.leaf": "Yaprak [{index}] = {value}.",
  "n.seg.combine": "Birleştir [{lo},{hi}] = {left} + {right} = {sum}.",
  "n.seg.built": "Segment ağacı kuruldu — kök toplamı = {sum}.",
  "n.seg.outside": "[{lo},{hi}], [{ql},{qr}] dışında — katkısı 0.",
  "n.seg.inside": "[{lo},{hi}] tamamen içeride — {sum} alınıyor.",
  "n.seg.split": "[{lo},{hi}] kısmen örtüşüyor — bölünüyor.",
  "n.seg.total": "[{ql}, {qr}] aralığının toplamı = {total}.",

  "n.uf.makeSets": "makeSets({n}): her eleman rütbesi 0 olan kendi köküdür.",
  "n.uf.walk": "find({x}): {node} bir kök değil — parent[{node}] = {parent} izleniyor.",
  "n.uf.root": "find({x}) = {root} — kök, kümeyi temsil eder.",
  "n.uf.compressOne": "Yol sıkıştırma: {nodes} artık doğrudan {root} düğümünü gösteriyor.",
  "n.uf.compress": "Yol sıkıştırma: {nodes} artık doğrudan {root} düğümünü gösteriyor.",
  "n.uf.sameSet": "{op}: ikisi de zaten {root} kümesinde — yapacak bir şey yok.",
  "n.uf.unionLess": "{op}: rütbe {rankA} < {rankB} — kök {ra}, {rb} altına bağlanıyor.",
  "n.uf.unionGreater": "{op}: rütbe {rankA} > {rankB} — kök {rb}, {ra} altına bağlanıyor.",
  "n.uf.unionEqual":
    "{op}: rütbeler eşit — {rb}, {ra} altına bağlanıyor ve rank[{ra}] {rank} yapılıyor.",
  "n.uf.done":
    "Tamamlandı. find({key}) = {root}; tekrarlanan find'lar ormanı düzleştirdi.",
};
